### ISSUE TITLE
The Octave-4.4.0-rc1 crashes with OS 10.9.5

### ISSUE THREAD

**Issue by bnzf** [octave-app/octave-app-bundler#48]
Octave form the Octave-4.4.0-rc1.dmg crashes right at startup with OS 10.9.5.
The crash report from the Konsole is attached.
[crash report.txt](https://github.com/octave-app/octave-app-bundler/files/2360772/crash.report.txt)

**Comment by apjanke** [comment]
Unfortunately, this is expected. The minimum required OS X version for Octave.app is 10.11 El Capitan. (We can't currently make the build work with earlier versions due to GCC compatibility issues; see https://github.com/octave-app/octave-app-bundler/issues/44#issuecomment-407960941.)

Sorry about that.

We should have a better error message, though. Just crashing sucks. It should pop up a dialog describing the minimum OS requirements, instead of crashing. Added a TODO: #49. Sorry about the bad user experience here.
